import { cookies } from "next/headers";
import { Crown, Gem, Globe, Trophy, Zap } from "lucide-react";

import { PrivateCaptureClient } from "@/components/PrivateCaptureClient";
import { LIVE_MICROTEST_ACCESS_COOKIE, hasValidLiveMicrotestAccess, isLiveMicrotestEnabled, isPublicPrivateCaptureEnabled } from "@/lib/live-microtest";
import { getAppState } from "@/lib/state";

export const dynamic = "force-dynamic";

export default async function HomePage({ searchParams }: { searchParams: Promise<{ private_capture?: string; capture_token?: string }> }) {
  const state = getAppState();
  const params = await searchParams;
  const cookieStore = await cookies();
  const captureEnabled = isPublicPrivateCaptureEnabled() || (params.private_capture === "1" && isLiveMicrotestEnabled() && hasValidLiveMicrotestAccess(params.capture_token) && hasValidLiveMicrotestAccess(cookieStore.get(LIVE_MICROTEST_ACCESS_COOKIE)?.value));
  const king = state.currentKing;
  return <main className="min-h-screen bg-[#08080c] px-4 py-6 font-mono text-white selection:bg-yellow-500 selection:text-black sm:py-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-col justify-between gap-4 border-b border-cyber-border/80 pb-6 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="rounded-lg border border-yellow-500/40 bg-yellow-500/20 p-1.5 text-yellow-400"><Crown className="h-5 w-5" /></span><h1 className="text-glow-gold text-2xl font-black tracking-tight sm:text-3xl">KING OF THE SCREEN</h1></div><p className="mt-1 text-xs text-gray-400 sm:text-sm">One screen. One ruler. Hold it until you get dethroned.</p></div><div className="flex items-center gap-3 text-xs"><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-emerald-400">● LIVE PRODUCTION TEST</span><span className="rounded-xl bg-yellow-400 px-4 py-3 font-black text-black">$0.95 CAPTURE</span></div></header>
    <section className="relative mx-auto w-full max-w-5xl overflow-hidden rounded-2xl border-2 border-yellow-500/50 bg-gradient-to-b from-[#141422] to-[#0d0d15] p-5 shadow-2xl sm:p-7"><div className="absolute -right-12 -top-12 h-64 w-64 rounded-full bg-yellow-500/10 blur-3xl" /><div className="relative mx-auto mb-6 max-w-3xl space-y-3 text-center"><span className="inline-flex items-center gap-2 rounded-full border border-yellow-500/30 bg-yellow-500/10 px-3.5 py-1.5 text-xs font-bold tracking-wider text-yellow-400"><Gem className="h-4 w-4" /> ONE SCREEN. ONE KING.</span><h2 className="text-2xl font-black leading-tight tracking-tight sm:text-4xl">TAKE THE SCREEN. <span className="text-yellow-400">LEAVE YOUR RECORD.</span></h2><p className="mx-auto max-w-2xl text-xs leading-relaxed text-gray-300 sm:text-base">Connect your wallet, add your image and message, then capture the throne through Phantom.</p></div><div className="grid grid-cols-1 gap-3.5 sm:grid-cols-3">{[["1", "Wallet", "Connect Phantom"], ["2", "Screen", "Add image and message"], ["3", "Crown", "Confirm your capture"]].map(([number, label, description]) => <article key={number} className="space-y-2 rounded-xl border border-cyber-border/80 bg-black/60 p-4"><div className="flex items-center gap-2 text-sm font-bold text-yellow-300"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-yellow-500/40 bg-yellow-500/20 text-xs font-black">{number}</span><Zap className="h-4 w-4" /> {label}</div><p className="text-xs leading-relaxed text-gray-400">{description}</p></article>)}</div></section>
    <section className="relative mx-auto w-full max-w-5xl overflow-hidden rounded-2xl border-2 border-yellow-500/80 bg-cyber-card shadow-[0_0_50px_rgba(234,179,8,0.35)]"><div className="relative min-h-[320px] bg-black sm:min-h-[460px]"><img src={king.mediaUrl} alt="Current King" className="absolute inset-0 h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-black/10" /><div className="relative flex min-h-[320px] items-end p-6 sm:min-h-[460px] sm:p-10"><div><span className="rounded-md bg-gradient-to-r from-yellow-400 to-amber-500 px-3 py-1 text-xs font-black uppercase tracking-wider text-black">CURRENT KING</span><h2 className="mt-4 text-4xl font-black text-white sm:text-6xl">{king.nickname}</h2><p className="mt-3 max-w-2xl text-base text-slate-200 sm:text-xl">{king.tagline}</p>{king.link && <a href={king.link} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-cyan-200 underline">{king.link}</a>}</div></div></div><div className="space-y-5 border-t-2 border-yellow-500/40 bg-[#11111c] p-5 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-cyber-border/60 pb-3"><span className="text-glow-gold flex items-center gap-2 text-2xl font-black tracking-wide sm:text-4xl">👑 CROWN RECORD</span><span className="rounded-md bg-yellow-400 px-3 py-1 text-xs font-black text-black">STAGE 1 TEST</span></div><div className="flex flex-col justify-between gap-4 rounded-2xl border-2 border-cyan-400 bg-gradient-to-r from-[#032b36] via-[#051d24] to-[#032b36] p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3.5"><span className="rounded-xl bg-cyan-400 p-3 text-black"><Globe className="h-6 w-6" /></span><div><span className="block text-[11px] font-black tracking-widest text-cyan-300">LIVE MAINNET TEST</span><span className="block text-lg font-black text-white sm:text-2xl">80% TREASURY. 20% OPERATIONS.</span></div></div><span className="rounded-xl bg-cyan-400 px-6 py-3 text-center text-sm font-black tracking-wider text-black">$0.95</span></div>{captureEnabled && <PrivateCaptureClient currentKing={king.nickname} token={params.capture_token} />}</div><div className="flex items-center justify-between border-t border-cyber-border bg-black/95 px-4 py-2 text-[11px] text-gray-400"><span className="flex items-center gap-2 text-emerald-400"><i className="h-2.5 w-2.5 rounded-full bg-emerald-500" /> SOLANA MAINNET</span><span className="hidden text-yellow-400 sm:block">NFT AND KOTS OFF</span></div></section>
    <section className="relative mx-auto w-full max-w-5xl overflow-hidden rounded-2xl border border-cyber-border bg-cyber-card p-4 shadow-xl sm:p-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-4 border-b border-cyber-border pb-4"><span className="flex items-center gap-2 text-base font-bold text-gold-400 sm:text-lg"><Trophy className="h-5 w-5 text-yellow-400" /> CROWN ARCHIVE</span><span className="rounded-xl border border-cyber-border bg-black/60 px-3 py-1.5 text-xs text-gray-400">TIMELINE</span></div>{state.hallOfFame.length ? <div className="space-y-3">{state.hallOfFame.slice(0, 10).map((entry) => <article key={entry.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/30 p-4"><div><b>{entry.nickname}</b><p className="mt-1 text-xs text-gray-400">{entry.tagline}</p></div><span className="text-sm font-black text-yellow-300">${entry.paidAmountUsd.toFixed(2)}</span></article>)}</div> : <div className="py-10 text-center text-xs text-gray-500"><Crown className="mx-auto mb-2 h-8 w-8 opacity-50" /><p>The first successful capture appears here.</p></div>}</section>
    <footer className="border-t border-cyber-border/80 pb-12 pt-8 text-center text-xs text-gray-500"><div className="flex items-center justify-center gap-2 font-bold text-gray-300"><Crown className="h-4 w-4 text-yellow-400" /> KING OF THE SCREEN (2026)</div><p className="mt-2">Stage 1. Payment, screen record, and archive. NFT and KOTS are off.</p></footer>
  </div></main>;
}
